name: my-pretty-javafx-pipeline
run-name: Testing the sample game with Playwright then deploy to GitHub pages
# Will be launched in case of...
on:
  # ...a push.
  push:
    branches: ["githubPipelineTests"]
    # ...a manual from the Actions tab
    workflow_dispatch:
jobs:
  building-my-pretty-PAN-artifact:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: building my pretty PAN artifact
      run: |
          mvn clean install -Djavafx.platform=win -P windows-build,dl-windows-jdk
          ls target