name: my-pretty-javafx-pipeline
run-name: Building PAN and uploading artifact
# Will be launched in case of...
on:
  # ...a push.
  push:
    branches: ["githubPipelineTests"]
    # ...a manual from the Actions tab
  workflow_dispatch:
jobs:
  building-my-pretty-PAN-artifact:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: building my pretty PAN artifact
      run: |
          mvn clean install -Djavafx.platform=win -P windows-build,dl-windows-jdk
          ls target
    - name: Generate artifact name
      id: generate-name
      run: |
        echo "::set-output name=artifact::${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}.zip"  
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.generate-name.outputs.artifact }}
        path: target/*.jar