name: my-pretty-javafx-pipeline
run-name: Testing the sample game with Playwright then deploy to GitHub pages
# Will be launched in case of...
on:
  # ...a push.
  push:
    branches: ["githubPipelineTests"]
    # ...a manual from the Actions tab
    workflow_dispatch:
jobs:
  testing-cyoa-engine-using-playwright:
    timeout-minutes: 60
    runs-on: maven:3.8.4-openjdk-17
    steps:
    - name: building ny pretty artifact
      run: |
          mvn clean install -Djavafx.platform=win -P windows-build,dl-windows-jdk
          ls target